//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katmanlı_ASP.NET_MVC_Web_API_MVC_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string MembershipType { get; set; }
        public Nullable<System.DateTime> MembershipEnding { get; set; }
        public Nullable<decimal> AnnualFee { get; set; }
    }
}
