//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katmanlı_ASP.NET_MVC_Web_API_MVC_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int EquipmentNo { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentType { get; set; }
        public string EquipmentCount { get; set; }
        public Nullable<decimal> EquipmentPrice { get; set; }
    }
}
