//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katmanlı_ASP.NET_MVC_Web_API_MVC_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelNo { get; set; }
        public string PersonelName { get; set; }
        public string PersonelPhone { get; set; }
        public string PersonelAddress { get; set; }
        public string PersonelType { get; set; }
    }
}
