//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katmanlı_ASP.NET_MVC_Web_API_MVC_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saloon
    {
        public int SaloonNo { get; set; }
        public string SaloonAddress { get; set; }
        public Nullable<decimal> SaloonPrice { get; set; }
        public string PersonelCount { get; set; }
        public string CustomerCount { get; set; }
        public string SaloonType { get; set; }
    }
}
